---
roles:
  - name: "genlab.semaphore"
    src: "https://github.com/corvus-migratorius/ansible-ara.git"

  - name: "genlab.docker_ubuntu"
    src: "https://github.com/corvus-migratorius/ansible-docker-ubuntu.git"
  
  - name: "genlab.postgresql_docker"
    src: "https://github.com/corvus-migratorius/ansible-postgresql-docker.git"
